Testing Mode: true

Grimmoire Properties:
  Material: WRITTEN_BOOK
  Display Name: "Grimmoire of %name%"
  Lore:
    - "&fTier: %tierNum% &f(%rarity%&f)"
    - "&fClass: %class%"

Base Mana:
  Tier 2: 1000
  Tier 3: 1500
  Tier 4: 2000
  Tier 5: 2500

Obtaining Chance:
  Tier 2: 50
  Tier 3: 35
  Tier 4: 10
  Tier 5: 5

# Please don't touch these 2 lines
Acquisition Info:
  Tier 4:
    Who Has It:
  Tier 5:
    Who Has It:


