Testing Mode: true

# Grimmoire Display Properties.
Grimmoire Properties:
  Material: WRITTEN_BOOK
  Display Name: "Grimmoire of %name%"
  Lore:
    - "&fTier: %tierNum% &f(%rarity%&f)"
    - "&fClass: %class%"

# The amount of mana regen that occurs per second (Without Tier Multipliers)
Base Mana Regen: 50

# Tier Properties
## Base Mana
## Obtaining Chance
## Mana Regen Multiplier
Tier Properties:
  Tier 2:
    # The starting mana for a tier. (Without upgrades)
    Max Mana: 1000
    # The chance at which a player has at obtaining this tier grimmoire
    Obtaining Chance: 50
    # It takes the "Base Mana Regen" and multiplies it by this number. That's how much the player regenerates mana per second.
    Mana Regen Multiplier: 1
  Tier 3:
    Max Mana: 1500
    Obtaining Chance: 35
    Mana Regen Multiplier: 1.25
  Tier 4:
    Max Mana: 2000
    Obtaining Chance: 10
    Mana Regen Multiplier: 2
  Tier 5:
    Max Mana: 2500
    Obtaining Chance: 5
    Mana Regen Multiplier: 5

# Please don't touch these 2 lines
Acquisition Info:
  Tier 4:
    Who Has It:
  Tier 5:
    Who Has It:


